

# Yes — layout is how the elements of your webpage are arranged/positioned on the screen.
layout: stacked
style: dark # background


title: Tommy Thompson
description: Software Engineer passionate about AI and finetuning models.
email: tommythompson@icloud.com
github_username:  tmumkadie


plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji


github: [metadata]

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options:
    pushed
     stars
  limit: 2
  exclude:
    archived: true
    forks: true
    projects:
      #repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  X: "@mumkadie2012"
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: "@tommythompson9828"


topics:
  - name: Artificial Intelligence
    web_url: https://github.com/topics/artificial-intelligence
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/machine-learning/machine-learning.png

  - name: Large Language Models
    web_url: https://github.com/topics/llm
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/tensorflow/tensorflow.png

  - name: Cybersecurity
    web_url: https://github.com/topics/cybersecurity
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png

  - name: DevOps
    web_url: https://github.com/topics/devops
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: Computer Vision
    web_url: https://github.com/topics/computer-vision
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Web3
    web_url: https://github.com/topics/web3
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/ethereum/ethereum.png